#ifndef		STEPPER__CONFIG_H_
#define		STEPPER__CONFIG_H_

#define STEPPER_PORT						DIO_u8PORTC
#define STEPPER_PIN_BLUE				DIO_u8PIN0
#define STEPPER_PIN_PINK				DIO_u8PIN1
#define STEPPER_PIN_YELLOW			DIO_u8PIN2
#define STEPPER_PIN_ORANGE			DIO_u8PIN3

#endif